1. Create an array.

In [ ]:
import numpy as np


marks_subject1 = np.array([85,88,90,75,92,80,85,78,88,95])
marks_subject2 = np.array([78,79,88,85,91,76,82,89,84,87])
marks_subject3 = np.array([92,85,76,89,83,85,90,94,78,92])

print(marks_subject1)
print(marks_subject2)
print(marks_subject3)

[85 88 90 75 92 80 85 78 88 95]
[78 79 88 85 91 76 82 89 84 87]
[92 85 76 89 83 85 90 94 78 92]


2. Basic statistics: mean,median,standard deviation

In [ ]:
mean_marks1 = np.mean(marks_subject1)
median_marks1 = np.median(marks_subject1)
stddev_marks1 = np.std(marks_subject1)

print("Mean:", mean_marks1)
print("Median:", median_marks1)
print("Standard  Deviation:", stddev_marks1)

Mean: 85.6
Median: 86.5
Standard  Deviation: 6.019966777316965


3. Reshape the array in a 2x5 matrix.

In [ ]:
reshaped_marks1 = marks_subject1.reshape(2,5)
print(reshaped_marks1)

[[85 88 90 75 92]
 [80 85 78 88 95]]


4. Access elements: access the element at row 1, column 2 of the reshaped array.

In [ ]:
element_row1_col2 = reshaped_marks1[1,2]
print(element_row1_col2)

78


5. Slicing: Slice the array to get the first 3 elements.

In [ ]:
first3_elements = marks_subject1[0:3]
print(first3_elements)

[85 88 90]


6. Element-wise Operations: Add 5 to each element in the array.

In [ ]:
add_5 = marks_subject1 + 5
print(add_5)

[ 90  93  95  80  97  85  90  83  93 100]


7. Broadcasting: Multiply each element in the array by 2 using broadcasting.

In [ ]:
multiply_2 = marks_subject1 * 2
print(multiply_2)

[170 176 180 150 184 160 170 156 176 190]


8. Matrix Multiplication: Create another array of shape (5, 2) and perform matrix multiplication.

In [ ]:
an_array = np.random.randint(1,10,(2,5))
reshaped_marks1_mult = reshaped_marks1.reshape(5,2)
matrix_product = np.dot(reshaped_marks1_mult, an_array)
print(matrix_product)

[[ 519  604 1038 1029  683]
 [ 495  585  990 1035  705]
 [ 516  608 1032 1068  724]
 [ 489  574  978  999  673]
 [ 549  637 1098 1077  711]]


9. Transpose: Transpose the reshaped 2x5 array.

In [ ]:
transpose_reshaped = reshaped_marks1.T
print(transpose_reshaped)

[[85 80]
 [88 85]
 [90 78]
 [75 88]
 [92 95]]


10. Flatten: Flatten the 2x5 array back into a 1D array.

In [ ]:
flat_array = reshaped_marks1.flatten()
print(flat_array)

[85 88 90 75 92 80 85 78 88 95]


11. Concatenate: Concatenate the arrays of 'marks_subject1' and 'marks_subject2'.

In [ ]:
marks_subject1 = np.array([85,88,90,75,92,80,85,78,88,95])
marks_subject2 = np.array([78,79,88,85,91,76,82,89,84,87])

concatenated_array = np.concatenate((marks_subject1, marks_subject2))
print(concatenated_array)

[85 88 90 75 92 80 85 78 88 95 78 79 88 85 91 76 82 89 84 87]


12. Unique Values: Find the unique values in the concatenated array.

In [ ]:
unique_values = np.unique(concatenated_array)
print(unique_values)

[75 76 78 79 80 82 84 85 87 88 89 90 91 92 95]


13. Filter Values: Filter the values that are greater than 80 in the 'marks_subject1' array.

In [ ]:
marks_subject1 = np.array([85,88,90,75,92,80,85,78,88,95])

filtered_array = marks_subject1[marks_subject1 > 80]
print(filtered_array)

[85 88 90 92 85 88 95]


14. Sort Array: Sort the 'marks_subject2' array.

In [ ]:
sorted_marks2 = np.sort(marks_subject2)
print(sorted_marks2)

[76 78 79 82 84 85 87 88 89 91]


15. Stack Arrays: Stack 'marks_subject1' and 'marks_subject2' vertically.

In [ ]:
stacked_arrays = np.vstack((marks_subject1, marks_subject2))
print(stacked_arrays)

[[85 88 90 75 92 80 85 78 88 95]
 [78 79 88 85 91 76 82 89 84 87]]


16. Split Array: Split the 'marks_subject1' array into two equal parts.

In [ ]:
split_arrays = np.split(marks_subject1, 2)
print(split_arrays)

[array([85, 88, 90, 75, 92]), array([80, 85, 78, 88, 95])]


17. Replace Values: Replace all elements greater than 85 in the 'marks_subject3' array with 85.

In [ ]:
marks_subject3 = np.array([92,85,76,89,83,85,90,94,78,92])

marks_subject3[marks_subject3 > 85] = 85
print(marks_subject3)

[85 85 76 85 83 85 85 85 78 85]


18. Generate Random Numbers: Generate an array of 10 random numbers between 0 and 100.

In [ ]:
random_numbers = np.random.randint(0, 100, 10)
print(random_numbers)

[ 9 78 31 97 73 62 94 30 29 16]


19. Mean of Random Numbers: Calculate the mean of the random numbers generated.

In [ ]:
mean_random_numbers = np.mean(random_numbers)
print(mean_random_numbers)

51.9


20. Save and Load: Save the 'marks_subject1' array to a file and then load it back.

In [ ]:
np.save('marks_subject1.npy', marks_subject1)

loaded_marks_subject1 = np.load('marks_subject1.npy')
print(loaded_marks_subject1)

[85 88 90 75 92 80 85 78 88 95]
